version: '3.1'

services:
  springboot:
    image: rakeshsounddocker/java_web_app:4
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - 8080:8080
    networks:
    - springappnetwork  
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    
networks:
  springappnetwork:
    driver: bridge
